#define YAP_ROOTDIR       "/usr/local"
#define YAP_BINDIR	    "/usr/local/bin"
#define YAP_LIBDIR	    "/usr/local/lib/Yap"
#define YAP_SHAREDIR	    "/usr/local/share"
#define YAP_PL_SRCDIR	    "/usr/local/share/Yap/pl"
#define YAP_STARTUP   "startup.yss"
#define YAP_VERSION 60202
#define MYDDAS_VERSION	    "MYDDAS-0.9.1"
#define YAP_ARCH	    "x86_64-linux"
#define YAP_LIBS	    "-lresolv -lnss_dns -lnss_files -lcrypt -lstdc++ -lm  -lreadline -lncurses -lz -ldl -lnsl"
#define YAP_YAPLIB	    "libYap.a"
#define YAP_CC	    "gcc"
#define YAP_CFLAGS	    "-O3 -fomit-frame-pointer -Wall -Wstrict-prototypes -Wmissing-prototypes -g -O2 -DCUT_C=1  -DCOROUTINING=1 -DRATIONAL_TREES=1 -DDEPTH_LIMIT=1 -DHAVE_CONFIG_H -D_YAP_NOT_INSTALLED_=1 -I. -I./H -I./OPTYap -I./BEAM -I./MYDDAS"
#define YAP_LDFLAGS    "-rdynamic  -L/home/tiago/Tese/Tese/Aleph/yap-6.2.2 -Wl,-R/usr/local/lib -Wl,-R,/usr/local/lib/Yap"
#define YAP_SHLIB_SUFFIX    "." "so"
#define YAP_TIMESTAMP "1456327132"
#define YAP_SVERSION   "YAP 6.2.2 (x86_64-linux): Qua Fev 24 15:18:52 WET 2016"
